name: Changeset Check

on:
    pull_request:
        branches:
            - main
        paths:
            - 'packages/**'

jobs:
    changeset-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - name: Check for changeset file
              run: |
                    if git diff --name-only origin/main..HEAD -- '.changeset/' | grep -qE '^.changeset/.*\.md'; then
                        echo "Changeset file found!"
                    else
                        echo "No changeset file found."
                        exit 1
                    fi
