name: Comment PR lead time on merge

on:
    pull_request:
        branches:
            - main
            - beta
        types:
            - closed

jobs:
    comment-lead-time:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
            - uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { default: script } = await import('${{ github.workspace }}/.github/lib/lead-time.mjs');
                      await script(github, context);
