name: Fondue Documentation CI

on:
    pull_request:

# Ensures that only one workflow per branch will run at a time.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    storybook:
        name: Storybook
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v4

            - name: Use pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Build Fondue Icons
              run: pnpm build:icons

            - name: Build Fondue Tokens
              run: pnpm build:tokens

            - name: Build Storybook docs
              run: pnpm build:storybook
