name: Pull Request

on:
    pull_request:
        branches:
            - "main"

env:
    NODE_VERSION: 16
    CI: true
    CYPRESS_CACHE_FOLDER: cypress_cache

jobs:
    setup-project:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v3

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: Cache dependencies
              id: npm_cache
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      ${{ env.CYPRESS_CACHE_FOLDER }}
                  key: node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: node_modules-

            - name: Install dependencies
              if: steps.npm_cache.outputs.cache-hit != 'true'
              run: npm ci

    component-tests:
        runs-on: ubuntu-latest

        needs: [setup-project]

        strategy:
            # when one test fails, do not cancel the other
            # containers, because this will kill Cypress processes
            # leaving the Dashboard hanging ...
            # https://github.com/cypress-io/github-action/issues/48
            fail-fast: false
            matrix:
                containers: ["worker bee 1", "worker bee 2", "worker bee 3"]

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Cache dependencies
              id: npm_cache
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      ${{ env.CYPRESS_CACHE_FOLDER }}
                  key: node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: node_modules-

            - name: Component Tests
              run: npx cypress run-ct --record --key=${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --group component-tests --tag component-tests --parallel
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
