name: Pull Request Title

on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize
            - ready_for_review

jobs:
    pr-title-validation:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  types: |
                      feat
                      fix
                      chore
                      docs
                      build
                      refactor
                      perf
                      test
                      ci
