name: Pull Request

on:
    pull_request:
        branches:
            - 'main'

env:
    NODE_VERSION: 16
    CI: true
    CYPRESS_CACHE_FOLDER: cypress_cache

jobs:
    component-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Cache dependencies
              id: npm_cache
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      ${{ env.CYPRESS_CACHE_FOLDER }}
                  key: node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: node_modules-

            - name: Component Tests
              run: npm run test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
